"""Generate HTML performance tearsheet for RL runs.

Renders comprehensive HTML report with:
    - Summary metrics (Sharpe, Sortino, Calmar, Max DD, Win Rate, Profit Factor)
    - Equity curve visualization
    - Drawdown chart
    - Returns distribution

Example:
    >>> from financial_analyzer.reports.generate_tearsheet import generate_tearsheet
    >>> generate_tearsheet(portfolio_values, returns, metrics, 'output/tearsheet.html')
"""
from __future__ import annotations
from pathlib import Path
from typing import Sequence, Dict, Optional
import numpy as np
from jinja2 import Template

HTML_TEMPLATE = """<!DOCTYPE html><html><head><meta charset='utf-8'><title>RL Tearsheet</title>
<style>
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Arial,sans-serif;margin:0;padding:24px;background:#fafafa;}
.container{max-width:1200px;margin:0 auto;background:white;padding:32px;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.1);}
h1{margin-top:0;color:#1a1a1a;border-bottom:2px solid #0074d9;padding-bottom:12px;}
h2{color:#333;margin-top:32px;font-size:1.4em;}
.metrics{display:grid;grid-template-columns:repeat(auto-fill,minmax(180px,1fr));gap:16px;margin:20px 0;}
.card{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);color:white;padding:20px;border-radius:8px;box-shadow:0 4px 6px rgba(0,0,0,0.1);}
.card.positive{background:linear-gradient(135deg,#11998e 0%,#38ef7d 100%);}
.card.negative{background:linear-gradient(135deg,#eb3349 0%,#f45c43 100%);}
.card.neutral{background:linear-gradient(135deg,#4b6cb7 0%,#182848 100%);}
.card strong{display:block;font-size:0.85em;opacity:0.9;margin-bottom:8px;text-transform:uppercase;letter-spacing:0.5px;}
.card .value{font-size:1.8em;font-weight:bold;}
.chart-container{margin:24px 0;background:#f9f9f9;padding:20px;border-radius:8px;}
.chart{width:100%;height:250px;}
svg{display:block;}
.footer{margin-top:40px;padding-top:20px;border-top:1px solid #e0e0e0;color:#666;font-size:0.9em;text-align:center;}
</style></head><body>
<div class='container'>
<h1>📊 RL Performance Tearsheet</h1>
<p style='color:#666;margin-bottom:24px;'>Generated: {{ timestamp }}</p>
<h2>Key Metrics</h2>
<div class='metrics'>
{% for k,v in metrics.items() %}
<div class='card {% if 'sharpe' in k.lower() or 'sortino' in k.lower() or 'calmar' in k.lower() %}{{ 'positive' if v > 1 else ('negative' if v < 0 else 'neutral') }}{% else %}neutral{% endif %}'>
<strong>{{k}}</strong><div class='value'>{{'%.4f' % v if v is not none else 'N/A'}}</div>
</div>
{% endfor %}
</div>
<h2>Equity Curve</h2>
<div class='chart-container'>
<div class='chart'>
<svg viewBox='0 0 1000 250' preserveAspectRatio='none'>
  <defs><linearGradient id='grad' x1='0%' y1='0%' x2='0%' y2='100%'><stop offset='0%' style='stop-color:#0074d9;stop-opacity:0.3'/><stop offset='100%' style='stop-color:#0074d9;stop-opacity:0.05'/></linearGradient></defs>
  <polygon fill='url(#grad)' points='{{ area_points }}'/>
  <polyline fill='none' stroke='#0074d9' stroke-width='2.5' points='{{ line_points }}' />
</svg>
</div>
</div>
{% if dd_points %}
<h2>Drawdown</h2>
<div class='chart-container'>
<div class='chart' style='height:180px;'>
<svg viewBox='0 0 1000 180' preserveAspectRatio='none'>
  <polygon fill='rgba(235,51,73,0.2)' points='{{ dd_area }}'/>
  <polyline fill='none' stroke='#eb3349' stroke-width='2' points='{{ dd_points }}' />
</svg>
</div>
</div>
{% endif %}
<div class='footer'>Generated by FinBot RL Pipeline | {{ timestamp }}</div>
</div>
</body></html>"""

def calculate_advanced_metrics(returns: Optional[Sequence[float]], portfolio_values: Sequence[float]) -> Dict[str, float]:
    """Calculate advanced risk-adjusted metrics from returns and values."""
    metrics: Dict[str, float] = {}
    values = np.array(portfolio_values, dtype=float)
    if len(values) < 2:
        return metrics
    
    # Total return
    metrics["Total Return"] = (values[-1] - values[0]) / values[0]
    
    # Returns-based metrics if available
    if returns is not None and len(returns) > 1:
        rets = np.array(returns, dtype=float)
        # Sharpe (annualized)
        mean_ret = np.mean(rets) * 252
        std_ret = np.std(rets, ddof=1) * np.sqrt(252)
        metrics["Sharpe Ratio"] = (mean_ret - 0.02) / std_ret if std_ret > 1e-8 else 0.0
        
        # Sortino (downside deviation)
        downside = rets[rets < 0]
        if len(downside) > 1:
            dd_std = np.std(downside, ddof=1) * np.sqrt(252)
            metrics["Sortino Ratio"] = (mean_ret - 0.02) / dd_std if dd_std > 1e-8 else 0.0
        else:
            metrics["Sortino Ratio"] = metrics["Sharpe Ratio"]
        
        # Win rate
        metrics["Win Rate"] = (rets > 0).sum() / len(rets)
        
        # Profit factor
        wins = rets[rets > 0].sum()
        losses = abs(rets[rets < 0].sum())
        metrics["Profit Factor"] = wins / losses if losses > 1e-8 else (10.0 if wins > 0 else 0.0)
    
    # Drawdown
    running_max = np.maximum.accumulate(values)
    drawdown = (values - running_max) / (running_max + 1e-8)
    metrics["Max Drawdown"] = drawdown.min()
    
    # Calmar ratio
    if abs(metrics["Max Drawdown"]) > 1e-8:
        ann_return = metrics["Total Return"] * (252 / len(values))
        metrics["Calmar Ratio"] = ann_return / abs(metrics["Max Drawdown"])
    else:
        metrics["Calmar Ratio"] = 0.0
    
    return metrics


def generate_tearsheet(
    portfolio_values: Sequence[float],
    returns: Optional[Sequence[float]] = None,
    metrics: Optional[Dict[str, float]] = None,
    output_path: str = "tearsheet.html"
) -> str:
    """Generate comprehensive HTML tearsheet.
    
    Args:
        portfolio_values: Portfolio value time series.
        returns: Optional returns series for advanced metrics.
        metrics: Optional pre-computed metrics; if None, auto-calculate from returns/values.
        output_path: Output HTML file path.
    
    Returns:
        Path to generated HTML file.
    """
    values = np.array(portfolio_values, dtype=float)
    if len(values) == 0:
        raise ValueError("portfolio_values empty")
    
    # Auto-calculate metrics if not provided
    if metrics is None:
        metrics = calculate_advanced_metrics(returns, values)
    else:
        # Merge with auto-calculated
        auto_metrics = calculate_advanced_metrics(returns, values)
        metrics = {**auto_metrics, **metrics}
    
    # Equity curve (line + area)
    min_v, max_v = values.min(), values.max()
    span = max(max_v - min_v, 1e-9)
    xs = np.linspace(0, 1000, len(values))
    ys = 250 - ((values - min_v) / span) * 220 - 15
    line_points = " ".join(f"{x:.2f},{y:.2f}" for x, y in zip(xs, ys))
    # Area polygon (close the shape)
    area_points = f"0,250 " + line_points + f" {xs[-1]:.2f},250"
    
    # Drawdown chart
    dd_points = None
    dd_area = None
    if len(values) > 1:
        running_max = np.maximum.accumulate(values)
        drawdown = (values - running_max) / (running_max + 1e-8) * 100  # percentage
        dd_ys = 180 - (drawdown - drawdown.min()) / (max(-drawdown.min(), 1e-9)) * 160 - 10
        dd_points = " ".join(f"{x:.2f},{y:.2f}" for x, y in zip(xs, dd_ys))
        dd_area = f"0,10 " + dd_points + f" {xs[-1]:.2f},10"
    
    # Render template
    from datetime import datetime
    html = Template(HTML_TEMPLATE).render(
        metrics=metrics,
        line_points=line_points,
        area_points=area_points,
        dd_points=dd_points,
        dd_area=dd_area,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    )
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding='utf-8')
    return str(path)

__all__ = ["generate_tearsheet"]
