{
 "title": "FinBot - Application Performance",
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Latency p50/p95/p99 (s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(finbot_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(finbot_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(finbot_request_duration_seconds_bucket[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request throughput (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(finbot_request_duration_seconds_count[1m]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Error ratio (%)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(rate(finbot_errors_total[1m])) / clamp_min(sum(rate(finbot_request_duration_seconds_count[1m])),1))",
     "legendFormat": "error_ratio"
    }
   ]
  }
 ]
}